language: node_js
node_js:
  - "9"
services:
  - docker
cache:
  directories:
    - "node_modules"
before_deploy:
  - docker build -t dariusbakunas/home-api .
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master