version: '3'
services:
  home_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeportal-api
    ports:
      - "9990:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance