version: '3'
services:
  home_api:
    image: dariusbakunas/homeportal-api:latest
    container_name: homeportal-api
    ports:
      - "9990:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance